apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-credential-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/asankav/.kube"


kind: PersistentVolumeClaim
metadata:
  name: kube-credential-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi